---
apiVersion: v1
kind: Pod
metadata:
  name: coco-demo-01
  annotations:
    "io.containerd.cri.runtime-handler": "kata-qemu-coco-dev"
spec:
  runtimeClassName: kata-qemu-coco-dev
  containers:
    - name: busybox
      image: quay.io/prometheus/busybox:latest
      imagePullPolicy: Always
      command:
        - sleep
        - "infinity"
  restartPolicy: Never
