---
apiVersion: v1
kind: Pod
metadata:
  name: coco-demo-04
  annotations:
    "io.containerd.cri.runtime-handler": "kata-qemu-clh"
    io.katacontainers.config.hypervisor.kernel_params: " agent.aa_kbc_params=cc_kbc::http://192.168.122.153:31491"
spec:
  runtimeClassName: kata-clh
  containers:
  - name: busybox
    image: quay.io/prometheus/busybox:latest
    imagePullPolicy: Always
    command:
      - sh
      - -c
      - |
        wget -O- http://127.0.0.1:8006/cdh/resource/default/secret/1; sleep infinity        
  restartPolicy: Never
