---
apiVersion: v1
kind: Pod
metadata:
  name: coco-demo-03
  annotations:
    "io.containerd.cri.runtime-handler": "kata-clh"
    io.katacontainers.config.hypervisor.kernel_params: " agent.aa_kbc_params=cc_kbc::http://192.168.122.153:31491"
spec:
  runtimeClassName: kata-clh
  containers:
  - name: busybox
    image: quay.io/prometheus/busybox:latest
    imagePullPolicy: Always
    command:
      - sleep
      - "infinity"
  restartPolicy: Never
